logging:
  level:
    org.springframework.web: info
    com.github.binarywang.demo.wx.pay: debug
    com.github.binarywang.wxpay: debug

wx:
  pay:
    appId: #еѕ®дїЎе…¬дј—еЏ·ж€–иЂ…е°ЏзЁ‹еєЏз­‰зљ„appid
    mchId: #еѕ®дїЎж”Їд»е•†ж€·еЏ?    mchKey: #еѕ®дїЎж”Їд»е•†ж€·еЇ†й’Ґ
    subAppId: #жњЌеЉЎе•†жЁЎејЏдё‹зљ„е­ђе•†ж€·е…¬дј—иґ¦еЏ·ID
    subMchId: #жњЌеЉЎе•†жЁЎејЏдё‹зљ„е­ђе•†ж€·еЏ?    keyPath: # p12иЇЃд№¦зљ„дЅЌзЅ®пјЊеЏЇд»ҐжЊ‡е®љз»ќеЇ№и·Їеѕ„пјЊд№џеЏЇд»ҐжЊ‡е®љз±»и·Їеѕ„пј€д»Ґclasspath:ејўге¤ґпј‰